-- Insert sample products
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY, SKU, CREATED_AT, UPDATED_AT) 
VALUES ('Laptop HP', 'High-performance laptop with 16GB RAM', 899.99, 5, 'COMPUTERS', 'HP-001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY, SKU, CREATED_AT, UPDATED_AT) 
VALUES ('Dell Monitor 27"', '4K Ultra HD Monitor', 349.99, 12, 'MONITORS', 'DELL-M27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY, SKU, CREATED_AT, UPDATED_AT) 
VALUES ('Mechanical Keyboard', 'RGB Mechanical Gaming Keyboard', 129.99, 8, 'PERIPHERALS', 'KEY-001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY, SKU, CREATED_AT, UPDATED_AT) 
VALUES ('Wireless Mouse', 'Ergonomic 2.4GHz Wireless Mouse', 49.99, 20, 'PERIPHERALS', 'MOUSE-001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY, SKU, CREATED_AT, UPDATED_AT) 
VALUES ('USB-C Hub', '7-in-1 USB-C Hub with HDMI', 79.99, 15, 'ACCESSORIES', 'HUB-001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert sample orders
INSERT INTO ORDERS (ORDER_NUMBER, PRODUCT_ID, QUANTITY, TOTAL_PRICE, STATUS, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, CREATED_AT, UPDATED_AT) 
VALUES ('ORD-2026-001', 1, 1, 899.99, 'DELIVERED', 'John Smith', 'john@example.com', '+1-555-0101', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO ORDERS (ORDER_NUMBER, PRODUCT_ID, QUANTITY, TOTAL_PRICE, STATUS, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, CREATED_AT, UPDATED_AT) 
VALUES ('ORD-2026-002', 2, 2, 699.98, 'SHIPPED', 'Sarah Johnson', 'sarah@example.com', '+1-555-0102', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO ORDERS (ORDER_NUMBER, PRODUCT_ID, QUANTITY, TOTAL_PRICE, STATUS, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, CREATED_AT, UPDATED_AT) 
VALUES ('ORD-2026-003', 3, 3, 389.97, 'ORDERED', 'Mike Davis', 'mike@example.com', '+1-555-0103', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO ORDERS (ORDER_NUMBER, PRODUCT_ID, QUANTITY, TOTAL_PRICE, STATUS, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, CREATED_AT, UPDATED_AT) 
VALUES ('ORD-2026-004', 4, 5, 249.95, 'DELIVERED', 'Emily Chen', 'emily@example.com', '+1-555-0104', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
